name: tarea6
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  svg_flutter: ^0.0.1
  url_launcher: ^6.3.1
  #flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/saul.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/AgeStages/
    - assets/icon/
